### ISSUE TITLE
Improve error message when Flashing fails on Linux due to permissions issues

### ISSUE THREAD

**Issue by apockill** [elephantrobotics/myStudio#9]
Bug: 
Unable to flash a program to robot

GUI:
![image](https://user-images.githubusercontent.com/1740412/112771975-2e2d4900-8fe3-11eb-9569-f235acc020c3.png)

Relevant Logs: 
```shell
Serial port /dev/ttyUSB0
Traceback (most recent call last):
  File "serial/serialposix.py", line 322, in open
PermissionError: [Errno 13] Permission denied: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "esptool.py", line 4019, in <module>
  File "esptool.py", line 4012, in _main
  File "esptool.py", line 3601, in main
  File "esptool.py", line 271, in __init__
  File "serial/__init__.py", line 90, in serial_for_url
  File "serial/serialposix.py", line 325, in open
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
[29760] Failed to execute script esptool
```

Cause: 
Not running MyStudio with `sudo`

Solution:
`sudo MyStudio`

**Comment by zlj-zz** [comment]
Thank you. I got it.
